services:
  docker

install:
  - docker build -f spark_and_hadoop.dockerfile --tag spark-and-hadoop .
  - docker build -f spark_with_hadoop.dockerfile --tag spark-with-hadoop .

script:
  - docker run --rm spark-and-hadoop spark-shell --version
  - docker run --rm spark-whith-hadoop spark-shell --version
